// Cloudflare Worker — Day 07 "serverless at the edge" demo
// Routes:
//   /              → HTML page showing which edge location answered you
//   /api/whereami  → JSON: edge colo, your city/country, protocol, TLS
//   /api/time      → JSON: time in Kathmandu vs. UTC (computed at the edge)
//   /api/hello?name=Sita → JSON greeting (query params)
//   /api/views     → a cached response: run it twice and watch the cf-cache-status / age
//   anything else  → 404 JSON

const json = (data, init = {}) =>
  new Response(JSON.stringify(data, null, 2), {
    ...init,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "access-control-allow-origin": "*", // let your portfolio (another origin) call this API
      ...(init.headers || {}),
    },
  });

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const cf = request.cf || {};
    const t0 = Date.now();

    switch (url.pathname) {
      case "/api/whereami":
        return json({
          servedBy: cf.colo,
          you: { city: cf.city, region: cf.region, country: cf.country, timezone: cf.timezone },
          network: { asn: cf.asn, org: cf.asOrganization },
          httpProtocol: cf.httpProtocol,
          tlsVersion: cf.tlsVersion,
          workerMs: Date.now() - t0,
        });

      case "/api/time": {
        const now = new Date();
        return json({
          utc: now.toISOString(),
          kathmandu: now.toLocaleString("en-GB", { timeZone: "Asia/Kathmandu" }),
          yourZone: cf.timezone,
          yourTime: cf.timezone ? now.toLocaleString("en-GB", { timeZone: cf.timezone }) : null,
        });
      }

      case "/api/hello": {
        const name = (url.searchParams.get("name") || "student").slice(0, 40);
        return json({ message: `Namaste ${name}! Greetings from ${cf.colo} 👋`, owner: env.OWNER });
      }

      case "/api/views": {
        // Edge cache demo: the first request is a MISS, repeats within 30s are a HIT.
        const cache = caches.default;
        const key = new Request(url.toString(), request);
        let res = await cache.match(key);
        if (res) {
          res = new Response(res.body, res);
          res.headers.set("x-edge-cache", "HIT");
          return res;
        }
        res = json(
          { generatedAt: new Date().toISOString(), note: "Refresh within 30s — generatedAt won't change." },
          { headers: { "cache-control": "public, max-age=30", "x-edge-cache": "MISS" } }
        );
        ctx.waitUntil(cache.put(key, res.clone()));
        return res;
      }

      case "/":
        return new Response(page(cf, env), { headers: { "content-type": "text/html; charset=utf-8" } });

      default:
        return json({ error: "Not found", path: url.pathname }, { status: 404 });
    }
  },
};

function page(cf, env) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Edge Hello</title>
<style>
 body{margin:0;background:#0d1117;color:#e6edf3;font:16px/1.6 "Courier New",monospace;display:grid;place-items:center;min-height:100vh}
 .c{border:2px solid #2a3546;background:#151b26;padding:32px;max-width:560px}
 .n{background:#c8f135;color:#0d1117;font-weight:700;padding:4px 12px;font-size:28px}
 h1{font-family:Arial Black,sans-serif;margin:14px 0}
 b{color:#c8f135} a{color:#2bb5f0}
</style></head><body><div class="c">
 <span class="n">${cf.colo || "??"}</span>
 <h1>HELLO FROM THE EDGE</h1>
 <p>This HTML was generated by a Worker running in data centre <b>${cf.colo}</b>,
 near you in <b>${cf.city || "?"}, ${cf.country || "?"}</b>.</p>
 <p>Protocol: <b>${cf.httpProtocol}</b> · TLS: <b>${cf.tlsVersion}</b></p>
 <p>Try: <a href="/api/whereami">/api/whereami</a> · <a href="/api/time">/api/time</a> ·
 <a href="/api/hello?name=you">/api/hello?name=you</a> · <a href="/api/views">/api/views</a></p>
 <p style="color:#8b98a9">Deployed by ${env.OWNER || "a student"} · Day 07</p>
</div></body></html>`;
}
